kumuluzee:
  name: sso
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/Simple_JPA
      connection-url: jdbc:postgresql://localhost:5432/PRPO_JPA
      username: postgres
      password: postgres
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi
    ui:
      mapping: /openapi/ui
  security:
    keycloak:
      json: '{
              "realm": "master",
              "bearer-only": true,
              "auth-server-url": "http://localhost:8082/auth",
              "ssl-required": "external",
              "resource": "customers-api",
              "confidential-port": 0
          }'

